### ISSUE TITLE
access violation : `OSError: exception: access violation reading 0x0000000000000000`

### ISSUE THREAD

**Issue by dubusster** [IRFM/librir#6]
There are some issues with python tests for IRMovie generated from numpy arrays of shapes (10, 515, 640) and (10, 243, 320).

The issue seems to reside in the C part with an access violation : `OSError: exception: access violation reading 0x0000000000000000`

This occurs everytime the second image of the instantiated movie is called by the C function  [rir_video_io.load_image](https://github.com/IRFM/librir/blob/e920e6e7f8b8f203ffc0cc23dd81ce811e28d4db/librir/low_level/rir_video_io.py#L176)

Can you have a look @Thermadiag ? It might be nothing or related to my computer but it crashes everytime...

_Originally posted by @dubusster in https://github.com/IRFM/librir/issues/5#issuecomment-1551028368_

**Comment by dubusster** [comment]
You can use this snippet to test it

```bash
python -m pytest ./tests/python/test_IRMovie.py::test_save_movie_to_h264[array4]
```

**Comment by egrelier** [comment]
I have the same issue running the snippet above in a fresh clone of the repo, after checking out on branch fix-librir-migration and building librir.

**Comment by dubusster** [comment]
Apparently it occurs only on windows ([see CI job](https://github.com/IRFM/librir/actions/runs/5042726652))

**Comment by Thermadiag** [comment]
Corrected. Problem was the serializeTimePoint crashing when passing an invalid time_point object, which is the case for this test.
Also added lock guard for this function as std::gmtime is not thread safe.
